// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tparam.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_tparam_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_tparam_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ppatt.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_tparam_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_tparam_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_tparam_2eproto;
namespace org {
namespace infinity {
namespace idm {
class TrackParam;
struct TrackParamDefaultTypeInternal;
extern TrackParamDefaultTypeInternal _TrackParam_default_instance_;
}  // namespace idm
}  // namespace infinity
}  // namespace org
PROTOBUF_NAMESPACE_OPEN
template<> ::org::infinity::idm::TrackParam* Arena::CreateMaybeMessage<::org::infinity::idm::TrackParam>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace org {
namespace infinity {
namespace idm {

// ===================================================================

class TrackParam final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:org.infinity.idm.TrackParam) */ {
 public:
  inline TrackParam() : TrackParam(nullptr) {}
  ~TrackParam() override;
  explicit constexpr TrackParam(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TrackParam(const TrackParam& from);
  TrackParam(TrackParam&& from) noexcept
    : TrackParam() {
    *this = ::std::move(from);
  }

  inline TrackParam& operator=(const TrackParam& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrackParam& operator=(TrackParam&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrackParam& default_instance() {
    return *internal_default_instance();
  }
  static inline const TrackParam* internal_default_instance() {
    return reinterpret_cast<const TrackParam*>(
               &_TrackParam_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TrackParam& a, TrackParam& b) {
    a.Swap(&b);
  }
  inline void Swap(TrackParam* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrackParam* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TrackParam* New() const final {
    return new TrackParam();
  }

  TrackParam* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TrackParam>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TrackParam& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const TrackParam& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrackParam* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "org.infinity.idm.TrackParam";
  }
  protected:
  explicit TrackParam(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPatternsFieldNumber = 6,
    kNameFieldNumber = 1,
    kColorFieldNumber = 5,
    kVMaxFieldNumber = 2,
    kVMinFieldNumber = 3,
    kVDefaultFieldNumber = 4,
  };
  // repeated .org.infinity.idm.ParamPattern patterns = 6;
  int patterns_size() const;
  private:
  int _internal_patterns_size() const;
  public:
  void clear_patterns();
  ::org::infinity::idm::ParamPattern* mutable_patterns(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::ParamPattern >*
      mutable_patterns();
  private:
  const ::org::infinity::idm::ParamPattern& _internal_patterns(int index) const;
  ::org::infinity::idm::ParamPattern* _internal_add_patterns();
  public:
  const ::org::infinity::idm::ParamPattern& patterns(int index) const;
  ::org::infinity::idm::ParamPattern* add_patterns();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::ParamPattern >&
      patterns() const;

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string color = 5;
  void clear_color();
  const std::string& color() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_color(ArgT0&& arg0, ArgT... args);
  std::string* mutable_color();
  PROTOBUF_MUST_USE_RESULT std::string* release_color();
  void set_allocated_color(std::string* color);
  private:
  const std::string& _internal_color() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_color(const std::string& value);
  std::string* _internal_mutable_color();
  public:

  // double vMax = 2;
  void clear_vmax();
  double vmax() const;
  void set_vmax(double value);
  private:
  double _internal_vmax() const;
  void _internal_set_vmax(double value);
  public:

  // double vMin = 3;
  void clear_vmin();
  double vmin() const;
  void set_vmin(double value);
  private:
  double _internal_vmin() const;
  void _internal_set_vmin(double value);
  public:

  // double vDefault = 4;
  void clear_vdefault();
  double vdefault() const;
  void set_vdefault(double value);
  private:
  double _internal_vdefault() const;
  void _internal_set_vdefault(double value);
  public:

  // @@protoc_insertion_point(class_scope:org.infinity.idm.TrackParam)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::ParamPattern > patterns_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr color_;
  double vmax_;
  double vmin_;
  double vdefault_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_tparam_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TrackParam

// string name = 1;
inline void TrackParam::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& TrackParam::name() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.TrackParam.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TrackParam::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:org.infinity.idm.TrackParam.name)
}
inline std::string* TrackParam::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:org.infinity.idm.TrackParam.name)
  return _s;
}
inline const std::string& TrackParam::_internal_name() const {
  return name_.Get();
}
inline void TrackParam::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* TrackParam::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* TrackParam::release_name() {
  // @@protoc_insertion_point(field_release:org.infinity.idm.TrackParam.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void TrackParam::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:org.infinity.idm.TrackParam.name)
}

// double vMax = 2;
inline void TrackParam::clear_vmax() {
  vmax_ = 0;
}
inline double TrackParam::_internal_vmax() const {
  return vmax_;
}
inline double TrackParam::vmax() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.TrackParam.vMax)
  return _internal_vmax();
}
inline void TrackParam::_internal_set_vmax(double value) {
  
  vmax_ = value;
}
inline void TrackParam::set_vmax(double value) {
  _internal_set_vmax(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.TrackParam.vMax)
}

// double vMin = 3;
inline void TrackParam::clear_vmin() {
  vmin_ = 0;
}
inline double TrackParam::_internal_vmin() const {
  return vmin_;
}
inline double TrackParam::vmin() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.TrackParam.vMin)
  return _internal_vmin();
}
inline void TrackParam::_internal_set_vmin(double value) {
  
  vmin_ = value;
}
inline void TrackParam::set_vmin(double value) {
  _internal_set_vmin(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.TrackParam.vMin)
}

// double vDefault = 4;
inline void TrackParam::clear_vdefault() {
  vdefault_ = 0;
}
inline double TrackParam::_internal_vdefault() const {
  return vdefault_;
}
inline double TrackParam::vdefault() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.TrackParam.vDefault)
  return _internal_vdefault();
}
inline void TrackParam::_internal_set_vdefault(double value) {
  
  vdefault_ = value;
}
inline void TrackParam::set_vdefault(double value) {
  _internal_set_vdefault(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.TrackParam.vDefault)
}

// string color = 5;
inline void TrackParam::clear_color() {
  color_.ClearToEmpty();
}
inline const std::string& TrackParam::color() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.TrackParam.color)
  return _internal_color();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TrackParam::set_color(ArgT0&& arg0, ArgT... args) {
 
 color_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:org.infinity.idm.TrackParam.color)
}
inline std::string* TrackParam::mutable_color() {
  std::string* _s = _internal_mutable_color();
  // @@protoc_insertion_point(field_mutable:org.infinity.idm.TrackParam.color)
  return _s;
}
inline const std::string& TrackParam::_internal_color() const {
  return color_.Get();
}
inline void TrackParam::_internal_set_color(const std::string& value) {
  
  color_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* TrackParam::_internal_mutable_color() {
  
  return color_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* TrackParam::release_color() {
  // @@protoc_insertion_point(field_release:org.infinity.idm.TrackParam.color)
  return color_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void TrackParam::set_allocated_color(std::string* color) {
  if (color != nullptr) {
    
  } else {
    
  }
  color_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), color,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:org.infinity.idm.TrackParam.color)
}

// repeated .org.infinity.idm.ParamPattern patterns = 6;
inline int TrackParam::_internal_patterns_size() const {
  return patterns_.size();
}
inline int TrackParam::patterns_size() const {
  return _internal_patterns_size();
}
inline ::org::infinity::idm::ParamPattern* TrackParam::mutable_patterns(int index) {
  // @@protoc_insertion_point(field_mutable:org.infinity.idm.TrackParam.patterns)
  return patterns_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::ParamPattern >*
TrackParam::mutable_patterns() {
  // @@protoc_insertion_point(field_mutable_list:org.infinity.idm.TrackParam.patterns)
  return &patterns_;
}
inline const ::org::infinity::idm::ParamPattern& TrackParam::_internal_patterns(int index) const {
  return patterns_.Get(index);
}
inline const ::org::infinity::idm::ParamPattern& TrackParam::patterns(int index) const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.TrackParam.patterns)
  return _internal_patterns(index);
}
inline ::org::infinity::idm::ParamPattern* TrackParam::_internal_add_patterns() {
  return patterns_.Add();
}
inline ::org::infinity::idm::ParamPattern* TrackParam::add_patterns() {
  ::org::infinity::idm::ParamPattern* _add = _internal_add_patterns();
  // @@protoc_insertion_point(field_add:org.infinity.idm.TrackParam.patterns)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::ParamPattern >&
TrackParam::patterns() const {
  // @@protoc_insertion_point(field_list:org.infinity.idm.TrackParam.patterns)
  return patterns_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace idm
}  // namespace infinity
}  // namespace org

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_tparam_2eproto
