// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tparam.proto

#include "tparam.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace org {
namespace infinity {
namespace idm {
constexpr TrackParam::TrackParam(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : patterns_()
  , name_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , color_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , vmax_(0)
  , vmin_(0)
  , vdefault_(0){}
struct TrackParamDefaultTypeInternal {
  constexpr TrackParamDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~TrackParamDefaultTypeInternal() {}
  union {
    TrackParam _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT TrackParamDefaultTypeInternal _TrackParam_default_instance_;
}  // namespace idm
}  // namespace infinity
}  // namespace org
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_tparam_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_tparam_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_tparam_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_tparam_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::org::infinity::idm::TrackParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::org::infinity::idm::TrackParam, name_),
  PROTOBUF_FIELD_OFFSET(::org::infinity::idm::TrackParam, vmax_),
  PROTOBUF_FIELD_OFFSET(::org::infinity::idm::TrackParam, vmin_),
  PROTOBUF_FIELD_OFFSET(::org::infinity::idm::TrackParam, vdefault_),
  PROTOBUF_FIELD_OFFSET(::org::infinity::idm::TrackParam, color_),
  PROTOBUF_FIELD_OFFSET(::org::infinity::idm::TrackParam, patterns_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::org::infinity::idm::TrackParam)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::org::infinity::idm::_TrackParam_default_instance_),
};

const char descriptor_table_protodef_tparam_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014tparam.proto\022\020org.infinity.idm\032\013ppatt."
  "proto\"\211\001\n\nTrackParam\022\014\n\004name\030\001 \001(\t\022\014\n\004vM"
  "ax\030\002 \001(\001\022\014\n\004vMin\030\003 \001(\001\022\020\n\010vDefault\030\004 \001(\001"
  "\022\r\n\005color\030\005 \001(\t\0220\n\010patterns\030\006 \003(\0132\036.org."
  "infinity.idm.ParamPatternb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_tparam_2eproto_deps[1] = {
  &::descriptor_table_ppatt_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_tparam_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_tparam_2eproto = {
  false, false, 193, descriptor_table_protodef_tparam_2eproto, "tparam.proto", 
  &descriptor_table_tparam_2eproto_once, descriptor_table_tparam_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_tparam_2eproto::offsets,
  file_level_metadata_tparam_2eproto, file_level_enum_descriptors_tparam_2eproto, file_level_service_descriptors_tparam_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_tparam_2eproto_getter() {
  return &descriptor_table_tparam_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_tparam_2eproto(&descriptor_table_tparam_2eproto);
namespace org {
namespace infinity {
namespace idm {

// ===================================================================

class TrackParam::_Internal {
 public:
};

void TrackParam::clear_patterns() {
  patterns_.Clear();
}
TrackParam::TrackParam(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  patterns_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:org.infinity.idm.TrackParam)
}
TrackParam::TrackParam(const TrackParam& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      patterns_(from.patterns_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArenaForAllocation());
  }
  color_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_color().empty()) {
    color_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_color(), 
      GetArenaForAllocation());
  }
  ::memcpy(&vmax_, &from.vmax_,
    static_cast<size_t>(reinterpret_cast<char*>(&vdefault_) -
    reinterpret_cast<char*>(&vmax_)) + sizeof(vdefault_));
  // @@protoc_insertion_point(copy_constructor:org.infinity.idm.TrackParam)
}

inline void TrackParam::SharedCtor() {
name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
color_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&vmax_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&vdefault_) -
    reinterpret_cast<char*>(&vmax_)) + sizeof(vdefault_));
}

TrackParam::~TrackParam() {
  // @@protoc_insertion_point(destructor:org.infinity.idm.TrackParam)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void TrackParam::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  color_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void TrackParam::ArenaDtor(void* object) {
  TrackParam* _this = reinterpret_cast< TrackParam* >(object);
  (void)_this;
}
void TrackParam::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TrackParam::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void TrackParam::Clear() {
// @@protoc_insertion_point(message_clear_start:org.infinity.idm.TrackParam)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  patterns_.Clear();
  name_.ClearToEmpty();
  color_.ClearToEmpty();
  ::memset(&vmax_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&vdefault_) -
      reinterpret_cast<char*>(&vmax_)) + sizeof(vdefault_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TrackParam::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "org.infinity.idm.TrackParam.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double vMax = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          vmax_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double vMin = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25)) {
          vmin_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double vDefault = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          vdefault_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // string color = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_color();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "org.infinity.idm.TrackParam.color"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .org.infinity.idm.ParamPattern patterns = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_patterns(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TrackParam::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:org.infinity.idm.TrackParam)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "org.infinity.idm.TrackParam.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // double vMax = 2;
  if (!(this->_internal_vmax() <= 0 && this->_internal_vmax() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_vmax(), target);
  }

  // double vMin = 3;
  if (!(this->_internal_vmin() <= 0 && this->_internal_vmin() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_vmin(), target);
  }

  // double vDefault = 4;
  if (!(this->_internal_vdefault() <= 0 && this->_internal_vdefault() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->_internal_vdefault(), target);
  }

  // string color = 5;
  if (!this->_internal_color().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_color().data(), static_cast<int>(this->_internal_color().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "org.infinity.idm.TrackParam.color");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_color(), target);
  }

  // repeated .org.infinity.idm.ParamPattern patterns = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_patterns_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, this->_internal_patterns(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:org.infinity.idm.TrackParam)
  return target;
}

size_t TrackParam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:org.infinity.idm.TrackParam)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .org.infinity.idm.ParamPattern patterns = 6;
  total_size += 1UL * this->_internal_patterns_size();
  for (const auto& msg : this->patterns_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string color = 5;
  if (!this->_internal_color().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_color());
  }

  // double vMax = 2;
  if (!(this->_internal_vmax() <= 0 && this->_internal_vmax() >= 0)) {
    total_size += 1 + 8;
  }

  // double vMin = 3;
  if (!(this->_internal_vmin() <= 0 && this->_internal_vmin() >= 0)) {
    total_size += 1 + 8;
  }

  // double vDefault = 4;
  if (!(this->_internal_vdefault() <= 0 && this->_internal_vdefault() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TrackParam::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    TrackParam::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TrackParam::GetClassData() const { return &_class_data_; }

void TrackParam::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<TrackParam *>(to)->MergeFrom(
      static_cast<const TrackParam &>(from));
}


void TrackParam::MergeFrom(const TrackParam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:org.infinity.idm.TrackParam)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  patterns_.MergeFrom(from.patterns_);
  if (!from._internal_name().empty()) {
    _internal_set_name(from._internal_name());
  }
  if (!from._internal_color().empty()) {
    _internal_set_color(from._internal_color());
  }
  if (!(from._internal_vmax() <= 0 && from._internal_vmax() >= 0)) {
    _internal_set_vmax(from._internal_vmax());
  }
  if (!(from._internal_vmin() <= 0 && from._internal_vmin() >= 0)) {
    _internal_set_vmin(from._internal_vmin());
  }
  if (!(from._internal_vdefault() <= 0 && from._internal_vdefault() >= 0)) {
    _internal_set_vdefault(from._internal_vdefault());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TrackParam::CopyFrom(const TrackParam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:org.infinity.idm.TrackParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrackParam::IsInitialized() const {
  return true;
}

void TrackParam::InternalSwap(TrackParam* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  patterns_.InternalSwap(&other->patterns_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &name_, GetArenaForAllocation(),
      &other->name_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &color_, GetArenaForAllocation(),
      &other->color_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TrackParam, vdefault_)
      + sizeof(TrackParam::vdefault_)
      - PROTOBUF_FIELD_OFFSET(TrackParam, vmax_)>(
          reinterpret_cast<char*>(&vmax_),
          reinterpret_cast<char*>(&other->vmax_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TrackParam::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_tparam_2eproto_getter, &descriptor_table_tparam_2eproto_once,
      file_level_metadata_tparam_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace idm
}  // namespace infinity
}  // namespace org
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::org::infinity::idm::TrackParam* Arena::CreateMaybeMessage< ::org::infinity::idm::TrackParam >(Arena* arena) {
  return Arena::CreateMessageInternal< ::org::infinity::idm::TrackParam >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
