// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: track.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_track_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_track_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "container.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_track_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_track_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_track_2eproto;
namespace org {
namespace infinity {
namespace idm {
class Track;
struct TrackDefaultTypeInternal;
extern TrackDefaultTypeInternal _Track_default_instance_;
}  // namespace idm
}  // namespace infinity
}  // namespace org
PROTOBUF_NAMESPACE_OPEN
template<> ::org::infinity::idm::Track* Arena::CreateMaybeMessage<::org::infinity::idm::Track>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace org {
namespace infinity {
namespace idm {

// ===================================================================

class Track final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:org.infinity.idm.Track) */ {
 public:
  inline Track() : Track(nullptr) {}
  ~Track() override;
  explicit constexpr Track(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Track(const Track& from);
  Track(Track&& from) noexcept
    : Track() {
    *this = ::std::move(from);
  }

  inline Track& operator=(const Track& from) {
    CopyFrom(from);
    return *this;
  }
  inline Track& operator=(Track&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Track& default_instance() {
    return *internal_default_instance();
  }
  static inline const Track* internal_default_instance() {
    return reinterpret_cast<const Track*>(
               &_Track_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Track& a, Track& b) {
    a.Swap(&b);
  }
  inline void Swap(Track* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Track* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Track* New() const final {
    return new Track();
  }

  Track* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Track>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Track& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Track& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Track* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "org.infinity.idm.Track";
  }
  protected:
  explicit Track(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContainersFieldNumber = 13,
    kNameFieldNumber = 1,
    kColorFieldNumber = 2,
    kMuteFieldNumber = 8,
    kSoloFieldNumber = 9,
    kGainFieldNumber = 10,
    kPanFieldNumber = 11,
    kMixFieldNumber = 12,
  };
  // repeated .org.infinity.idm.Container containers = 13;
  int containers_size() const;
  private:
  int _internal_containers_size() const;
  public:
  void clear_containers();
  ::org::infinity::idm::Container* mutable_containers(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::Container >*
      mutable_containers();
  private:
  const ::org::infinity::idm::Container& _internal_containers(int index) const;
  ::org::infinity::idm::Container* _internal_add_containers();
  public:
  const ::org::infinity::idm::Container& containers(int index) const;
  ::org::infinity::idm::Container* add_containers();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::Container >&
      containers() const;

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string color = 2;
  void clear_color();
  const std::string& color() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_color(ArgT0&& arg0, ArgT... args);
  std::string* mutable_color();
  PROTOBUF_MUST_USE_RESULT std::string* release_color();
  void set_allocated_color(std::string* color);
  private:
  const std::string& _internal_color() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_color(const std::string& value);
  std::string* _internal_mutable_color();
  public:

  // bool mute = 8;
  void clear_mute();
  bool mute() const;
  void set_mute(bool value);
  private:
  bool _internal_mute() const;
  void _internal_set_mute(bool value);
  public:

  // bool solo = 9;
  void clear_solo();
  bool solo() const;
  void set_solo(bool value);
  private:
  bool _internal_solo() const;
  void _internal_set_solo(bool value);
  public:

  // double gain = 10;
  void clear_gain();
  double gain() const;
  void set_gain(double value);
  private:
  double _internal_gain() const;
  void _internal_set_gain(double value);
  public:

  // double pan = 11;
  void clear_pan();
  double pan() const;
  void set_pan(double value);
  private:
  double _internal_pan() const;
  void _internal_set_pan(double value);
  public:

  // double mix = 12;
  void clear_mix();
  double mix() const;
  void set_mix(double value);
  private:
  double _internal_mix() const;
  void _internal_set_mix(double value);
  public:

  // @@protoc_insertion_point(class_scope:org.infinity.idm.Track)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::Container > containers_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr color_;
  bool mute_;
  bool solo_;
  double gain_;
  double pan_;
  double mix_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_track_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Track

// string name = 1;
inline void Track::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& Track::name() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Track.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Track::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:org.infinity.idm.Track.name)
}
inline std::string* Track::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:org.infinity.idm.Track.name)
  return _s;
}
inline const std::string& Track::_internal_name() const {
  return name_.Get();
}
inline void Track::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Track::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Track::release_name() {
  // @@protoc_insertion_point(field_release:org.infinity.idm.Track.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Track::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:org.infinity.idm.Track.name)
}

// string color = 2;
inline void Track::clear_color() {
  color_.ClearToEmpty();
}
inline const std::string& Track::color() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Track.color)
  return _internal_color();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Track::set_color(ArgT0&& arg0, ArgT... args) {
 
 color_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:org.infinity.idm.Track.color)
}
inline std::string* Track::mutable_color() {
  std::string* _s = _internal_mutable_color();
  // @@protoc_insertion_point(field_mutable:org.infinity.idm.Track.color)
  return _s;
}
inline const std::string& Track::_internal_color() const {
  return color_.Get();
}
inline void Track::_internal_set_color(const std::string& value) {
  
  color_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Track::_internal_mutable_color() {
  
  return color_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Track::release_color() {
  // @@protoc_insertion_point(field_release:org.infinity.idm.Track.color)
  return color_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Track::set_allocated_color(std::string* color) {
  if (color != nullptr) {
    
  } else {
    
  }
  color_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), color,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:org.infinity.idm.Track.color)
}

// bool mute = 8;
inline void Track::clear_mute() {
  mute_ = false;
}
inline bool Track::_internal_mute() const {
  return mute_;
}
inline bool Track::mute() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Track.mute)
  return _internal_mute();
}
inline void Track::_internal_set_mute(bool value) {
  
  mute_ = value;
}
inline void Track::set_mute(bool value) {
  _internal_set_mute(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.Track.mute)
}

// bool solo = 9;
inline void Track::clear_solo() {
  solo_ = false;
}
inline bool Track::_internal_solo() const {
  return solo_;
}
inline bool Track::solo() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Track.solo)
  return _internal_solo();
}
inline void Track::_internal_set_solo(bool value) {
  
  solo_ = value;
}
inline void Track::set_solo(bool value) {
  _internal_set_solo(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.Track.solo)
}

// double gain = 10;
inline void Track::clear_gain() {
  gain_ = 0;
}
inline double Track::_internal_gain() const {
  return gain_;
}
inline double Track::gain() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Track.gain)
  return _internal_gain();
}
inline void Track::_internal_set_gain(double value) {
  
  gain_ = value;
}
inline void Track::set_gain(double value) {
  _internal_set_gain(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.Track.gain)
}

// double pan = 11;
inline void Track::clear_pan() {
  pan_ = 0;
}
inline double Track::_internal_pan() const {
  return pan_;
}
inline double Track::pan() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Track.pan)
  return _internal_pan();
}
inline void Track::_internal_set_pan(double value) {
  
  pan_ = value;
}
inline void Track::set_pan(double value) {
  _internal_set_pan(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.Track.pan)
}

// double mix = 12;
inline void Track::clear_mix() {
  mix_ = 0;
}
inline double Track::_internal_mix() const {
  return mix_;
}
inline double Track::mix() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Track.mix)
  return _internal_mix();
}
inline void Track::_internal_set_mix(double value) {
  
  mix_ = value;
}
inline void Track::set_mix(double value) {
  _internal_set_mix(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.Track.mix)
}

// repeated .org.infinity.idm.Container containers = 13;
inline int Track::_internal_containers_size() const {
  return containers_.size();
}
inline int Track::containers_size() const {
  return _internal_containers_size();
}
inline ::org::infinity::idm::Container* Track::mutable_containers(int index) {
  // @@protoc_insertion_point(field_mutable:org.infinity.idm.Track.containers)
  return containers_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::Container >*
Track::mutable_containers() {
  // @@protoc_insertion_point(field_mutable_list:org.infinity.idm.Track.containers)
  return &containers_;
}
inline const ::org::infinity::idm::Container& Track::_internal_containers(int index) const {
  return containers_.Get(index);
}
inline const ::org::infinity::idm::Container& Track::containers(int index) const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Track.containers)
  return _internal_containers(index);
}
inline ::org::infinity::idm::Container* Track::_internal_add_containers() {
  return containers_.Add();
}
inline ::org::infinity::idm::Container* Track::add_containers() {
  ::org::infinity::idm::Container* _add = _internal_add_containers();
  // @@protoc_insertion_point(field_add:org.infinity.idm.Track.containers)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::Container >&
Track::containers() const {
  // @@protoc_insertion_point(field_list:org.infinity.idm.Track.containers)
  return containers_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace idm
}  // namespace infinity
}  // namespace org

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_track_2eproto
